[build]
  # 监听以下文件扩展名的文件.
  include_ext = ["go", "tpl", "tmpl", "html", "gohtml", "env"]
  # kill 命令延迟
  kill_delay = "0s"
  # air的日志文件名，该日志文件放置在你的`tmp_dir`中
  log = "air.log"
  # 在 kill 之前发送系统中断信号，windows 不支持此功能
  send_interrupt = false
  # error 发生时结束运行
  stop_on_error = true